[terminal.shell]
program = "/bin/zsh"

[colors.primary]
background = "#040404"
foreground = "#ffffff"

[colors.search]
matches = {foreground = "#161616", background = '#ee5396'}

[colors.normal]
black = "#262626"
green = "#ff7eb6"
red = "#33b1ff"
yellow = "#ffe97b"
blue = "#673ab7"
magenta = "#ee5396"
cyan = "#3ddbd9"
white = "#dde1e6"

[colors.bright]
black = "#393939"
green = "#ff7eb6"
red = "#42be65"
yellow = "#ffe97b"
blue = "#673ab7"
magenta = "#ee5396"
cyan = "#3ddbd9"
white = "#ffffff"

[font]
size = 9.5

[font.normal]
family = "JetBrainsMonoNerdFont"

[window]
title = "Terminal"
decorations = "None"
opacity = 1.0

[window.padding]
x = 10
y = 10

[cursor.style]
blinking = "On"
